version: 2
executorType: machine
stages:
  build:
    workDir: ~/mechanical
    steps:
      - type: checkout
      - type: shell
        name: Check Docker version
        command: |
          docker --version
          docker-compose --version
      - type: shell
        name: Build image
        command: |
          docker build -t quay.io/enykeev/mechanicabot:$CIRCLE_SHA1 .
      - type: deploy
        name: Deploy image to repository
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
          docker push quay.io/enykeev/mechanicabot:$CIRCLE_SHA1
